# Download node image from Docker Hub
FROM node:18.13.0-alpine as build

WORKDIR /app

COPY package.json .

# Install Angular CLI
RUN npm install @angular/cli

# Copy all files and install dependencies
COPY . .
RUN npm install

# Build the Angular project
RUN npm run build --prod
RUN ls -l /app/dist/dicegame

# Use stable NGINX version
FROM nginx:stable-alpine3.19

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Ensure the path matches the actual build output directory
COPY --from=build /app/dist/dicegame/browser /usr/share/nginx/html

EXPOSE 80

# Start NGINX server
ENTRYPOINT ["nginx", "-g", "daemon off;"]
